import { BASE_CSS } from './templates/base.css.js';
import { CLIENT_JS } from './templates/dashboard.client.js';
import { escapeHtml } from '../util/escape.js';

/**
 * @param {{generated_at:string, projects:any[], sessions:any[]}} index
 * @param {{fragments?: Record<string,string>, serve?: boolean}} [opts]
 */
export function renderDashboardHtml(index, opts = {}) {
  const fragments = opts.fragments ?? {};

  // Strip private fields from the JSON we ship to the browser.
  const sessionsForClient = index.sessions.map((s) => ({
    id: s.id,
    project_path: s.project_path,
    project_name: s.project_name,
    project_description: s.project_description ?? null,
    project_tags: s.project_tags ?? [],
    important_files: s.important_files ?? [],
    started_at: s.started_at,
    ended_at: s.ended_at,
    duration_seconds: s.duration_seconds,
    message_count: s.message_count,
    files_touched: s.files_touched,
    first_user_message: s.first_user_message,
    git_branch: s.git_branch,
    intervention_count: s.intervention_count,
    first_intervention: s.first_intervention ?? '',
    activity_buckets: s.activity_buckets ?? [],
    tool_calls: s.tool_calls,
    mcp_tools: s.mcp_tools ?? {},
    bash_categories: s.bash_categories ?? {},
    slash_commands: s.slash_commands ?? {},
    stop_reasons: s.stop_reasons ?? {},
    max_tokens_count: s.max_tokens_count ?? 0,
    refusal_count: s.refusal_count ?? 0,
    skills_used: s.skills_used ?? {},
    subagents_used: s.subagents_used ?? {},
    tokens: s.tokens ?? null,
    models: s.models ?? [],
    shared: s.shared ?? false,
    sidechain_messages: s.sidechain_messages ?? 0,
    tool_failures: s.tool_failures ?? 0,
    plan_turn_pct: s.plan_turn_pct ?? 0,
    plan_turns: s.plan_turns ?? 0,
    turn_duration_ms_avg: s.turn_duration_ms_avg ?? 0,
    turn_duration_ms_max: s.turn_duration_ms_max ?? 0,
    turn_count: s.turn_count ?? 0,
    summary: s.summary,
  }));

  const payload = {
    generated_at: index.generated_at,
    version: index.version,
    projects: index.projects,
    sessions: sessionsForClient,
  };

  // Stable JSON for byte-identical renders across runs.
  const payloadJson = JSON.stringify(payload);
  const fragmentsJson = JSON.stringify(fragments);

  const serveFlag = opts.serve ? 'window.__coding_agent_story_poll__ = true;' : '';

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>coding-agent-story dashboard</title>
<style>${BASE_CSS}</style>
</head>
<body>
<header class="coding-agent-story-header">
  <h1>coding-agent-story <span class="pill">local</span></h1>
  <span id="coding-agent-story-stats" class="stats"></span>
</header>
<main>
  <div class="toolbar">
    <input type="search" id="coding-agent-story-search" placeholder="Search summary, files, branch… (/)" autocomplete="off">
    <label for="coding-agent-story-project">project</label>
    <select id="coding-agent-story-project">
      <option value="all">all projects</option>
    </select>
    <label for="coding-agent-story-range">when</label>
    <select id="coding-agent-story-range">
      <option value="all">all time</option>
      <option value="24h">last 24h</option>
      <option value="7d">last 7d</option>
      <option value="30d">last 30d</option>
    </select>
    <label for="coding-agent-story-sort">sort</label>
    <select id="coding-agent-story-sort">
      <option value="recent">most recent</option>
      <option value="longest">longest</option>
      <option value="interventions">most interventions</option>
      <option value="files">most files</option>
      <option value="tokens">most tokens</option>
      <option value="failures">most failures</option>
    </select>
    <label><input type="checkbox" id="coding-agent-story-hasint"> has interventions</label>
    <div class="spacer"></div>
    <span class="meta"><kbd>/</kbd> search · <kbd>j</kbd>/<kbd>k</kbd> move · <kbd>↵</kbd> expand</span>
  </div>
  <div id="coding-agent-story-list" class="session-list"></div>
  <footer class="help-foot">Generated by coding-agent-story · all data stays on your machine. No network calls, no LLM calls.</footer>
</main>
<script type="application/json" id="coding-agent-story-data">${escapeForJsonScript(payloadJson)}</script>
<script type="application/json" id="coding-agent-story-fragments">${escapeForJsonScript(fragmentsJson)}</script>
<script>${serveFlag}${CLIENT_JS}</script>
</body>
</html>`;
}

// Escape "</" inside JSON payloads so they can't terminate the host
// <script type="application/json"> block.
function escapeForJsonScript(json) {
  return String(json).replace(/<\/(script)/gi, '<\\/$1');
}
