import { escapeHtml } from '../util/escape.js';
import { BASE_CSS } from './templates/base.css.js';
import { diffLines, collapseContext } from '../util/diff.js';
import { githubBlobUrl } from '../util/git.js';

/**
 * Render a PRStoryRich as a self-contained HTML page tailored for a
 * reviewer reading the PR file-by-file.
 * @param {import('../pr-build.js').PRStoryRich} story
 */
export function renderPrHtml(story) {
  const ctx = {
    branch: story.branch,
    github_base: story.github_base,
    repo_root: story.repo_root,
  };

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(`PR story — ${story.branch}`)}</title>
<style>${BASE_CSS}${PR_CSS}</style>
</head>
<body>
<header class="coding-agent-story-header">
  <h1>PR story <span class="pill">${escapeHtml(story.branch)}</span></h1>
  ${renderPrLink(story)}
  <span class="stats">${renderTotals(story.totals)}</span>
</header>
<main>
  ${renderBranchAndCommits(story)}
  ${renderOutcomesStrip(story.outcomes)}
  ${renderThrashSummary(story.files)}
  ${renderInterventionsAtTop(story.interventions)}
  <h2 class="section-h">Files in this PR (${story.files.length})</h2>
  ${story.files.length
    ? story.files.map((f, i) => renderFileSection(f, ctx, i === 0)).join('\n')
    : '<div class="empty">No file edits detected across the discovered sessions.</div>'}
  ${renderSessionsList(story)}
  <footer class="help-foot">Generated by coding-agent-story · all data stays on your machine.</footer>
</main>
</body>
</html>`;
}

const PR_CSS = `
  .section-h { margin: 28px 0 12px; font-size: 16px; letter-spacing: 0.2px; }
  .totals-pill { display: inline-block; padding: 2px 8px; border-radius: 999px; background: var(--panel-2); border: 1px solid var(--border); color: var(--muted); font-size: 11px; margin-right: 6px; }
  .pr-link {
    display: inline-block; margin-left: 8px;
    background: rgba(105,213,142,0.12); color: var(--green); border: 1px solid rgba(105,213,142,0.35);
    padding: 2px 10px; border-radius: 999px; font-size: 12px;
  }
  .pr-link.no-pr { background: var(--panel-2); color: var(--muted); border-color: var(--border); }
  .outcomes-strip {
    display: flex; gap: 8px; flex-wrap: wrap; margin: 8px 0 18px;
  }
  .outcome-chip {
    display: inline-flex; align-items: center; gap: 6px;
    padding: 4px 10px; border-radius: 999px;
    background: var(--panel-2); border: 1px solid var(--border);
    color: var(--muted); font-size: 12px;
  }
  .outcome-chip.pass { background: rgba(105,213,142,0.10); color: var(--green); border-color: rgba(105,213,142,0.30); }
  .outcome-chip.fail { background: rgba(255,107,107,0.10); color: var(--red); border-color: rgba(255,107,107,0.30); }
  .thrash-summary {
    background: var(--panel); border: 1px solid var(--border); border-radius: 8px;
    padding: 12px 14px; margin-bottom: 18px;
  }
  .thrash-summary h4 { margin: 0 0 8px; font-size: 12px; text-transform: uppercase; letter-spacing: 0.6px; color: var(--muted); }
  .thrash-summary table { width: 100%; border-collapse: collapse; font-size: 12px; }
  .thrash-summary td, .thrash-summary th { padding: 3px 6px; text-align: left; }
  .thrash-summary th { color: var(--muted); font-weight: normal; }
  .thrash-summary td.num { text-align: right; font-variant-numeric: tabular-nums; width: 60px; }
  .badge-align { padding: 1px 7px; border-radius: 999px; font-size: 10px; border: 1px solid transparent; margin-left: 6px; vertical-align: 1px; }
  .badge-align.kept       { background: rgba(105,213,142,0.10); color: var(--green); border-color: rgba(105,213,142,0.30); }
  .badge-align.reverted   { background: rgba(255,107,107,0.10); color: var(--red); border-color: rgba(255,107,107,0.30); }
  .badge-align.changed-later { background: rgba(255,209,102,0.10); color: var(--yellow); border-color: rgba(255,209,102,0.30); }
  .badge-align.not-in-pr  { background: var(--panel-2); color: var(--muted); border-color: var(--border); }
  .badge-align.unknown    { background: var(--panel-2); color: var(--muted); border-color: var(--border); font-style: italic; }
  .file-section {
    background: var(--panel); border: 1px solid var(--border); border-radius: 8px;
    margin: 10px 0; overflow: hidden; box-shadow: var(--shadow);
  }
  .file-section[open] { border-color: var(--accent); }
  .file-section summary {
    list-style: none; cursor: pointer; padding: 10px 14px;
    display: flex; flex-wrap: wrap; gap: 10px; align-items: center;
  }
  .file-section summary::-webkit-details-marker { display: none; }
  .file-section summary .fp {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 13px; color: var(--accent);
    word-break: break-all;
  }
  .file-section summary .badges { display: flex; gap: 4px; flex-wrap: wrap; }
  .file-section .body { padding: 8px 14px 16px; border-top: 1px solid var(--border); background: var(--panel-2); }
  .file-section .why { margin-bottom: 8px; }
  .file-section .why h5 { margin: 8px 0 4px; font-size: 11px; text-transform: uppercase; color: var(--muted); }
  .file-section .why ul { list-style: none; padding: 0; margin: 0; }
  .file-section .why li {
    padding: 6px 10px; background: var(--panel); border: 1px solid var(--border);
    border-radius: 4px; margin: 4px 0; font-size: 12px;
  }
  .file-section .why li.dec { border-left: 3px solid var(--accent); }
  .file-section .why li.int { border-left: 3px solid var(--yellow); background: rgba(255,209,102,0.06); }
  .commits {
    display: flex; flex-wrap: wrap; gap: 6px; margin: 6px 0 18px;
  }
  .commits .commit-pill {
    display: inline-flex; gap: 6px; align-items: center; padding: 2px 10px;
    border-radius: 999px; background: var(--panel); border: 1px solid var(--border);
    font-size: 11px;
  }
  .commits .commit-pill code { color: var(--accent); font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
`;

function renderTotals(t) {
  const tk = t.tokens;
  const tokPill = tk ? `<span class="totals-pill" title="${escapeHtml(tokenTooltip(tk))}">${fmtTokens(tk.billable)} tokens</span>` : '';
  return `<span class="totals-pill">${t.sessions} sessions</span>` +
    `<span class="totals-pill">${t.edits} edits</span>` +
    `<span class="totals-pill">${t.decisions} decisions</span>` +
    `<span class="totals-pill">${t.interventions} interventions</span>` +
    tokPill;
}

function fmtTokens(n) {
  n = +n || 0;
  if (n === 0) return '—';
  if (n < 1000) return String(n);
  if (n < 1e6) return (n / 1000).toFixed(n < 10000 ? 1 : 0) + 'k';
  return (n / 1e6).toFixed(1) + 'M';
}

function tokenTooltip(t) {
  return `in: ${(t.input||0).toLocaleString()} · out: ${(t.output||0).toLocaleString()}` +
    ` · cache_read: ${(t.cache_read||0).toLocaleString()} · cache_create: ${(t.cache_creation||0).toLocaleString()}` +
    ` · billable: ${(t.billable||0).toLocaleString()}`;
}

function renderPrLink(story) {
  if (!story.pr) return `<span class="pr-link no-pr">no open PR detected</span>`;
  const state = story.pr.state ? ` (${story.pr.state.toLowerCase()})` : '';
  return `<a class="pr-link" href="${escapeHtml(story.pr.url)}" target="_blank" rel="noopener">#${story.pr.number}${escapeHtml(state)} ↗</a>`;
}

function renderBranchAndCommits(story) {
  const branchPill = renderBranchPill(story);
  const commitPills = (story.commits ?? []).slice(0, 10).map((c) => {
    const href = story.github_base ? `${story.github_base}/commit/${c.hash}` : null;
    const text = `<code>${escapeHtml(c.short)}</code> <span>${escapeHtml(oneLine(c.subject))}</span>`;
    return href
      ? `<a class="commit-pill" href="${escapeHtml(href)}" target="_blank" rel="noopener">${text}</a>`
      : `<span class="commit-pill">${text}</span>`;
  }).join('');
  const more = story.commits.length > 10 ? `<span class="commit-pill">+${story.commits.length - 10} more</span>` : '';
  return `${branchPill}<div class="commits">${commitPills}${more}</div>`;
}

function renderBranchPill(story) {
  const inside = `⎇ ${escapeHtml(story.branch)}`;
  if (story.github_base && story.branch && story.branch !== 'HEAD') {
    const href = `${story.github_base}/tree/${encodeURIComponent(story.branch)}`;
    return `<a class="branch-pill" href="${href}" target="_blank" rel="noopener" title="view branch on GitHub">${inside}</a>`;
  }
  return `<span class="branch-pill">${inside}</span>`;
}

function renderOutcomesStrip(outcomes) {
  const s = outcomes?.summary;
  if (!s) return '';
  if (!(s.tests_run || s.lints_run || s.builds_run)) return '';
  const testCls = s.tests_failed > 0 ? 'fail' : s.tests_passed > 0 ? 'pass' : '';
  return `<div class="outcomes-strip">
    ${s.tests_run ? `<span class="outcome-chip ${testCls}">🧪 ${s.tests_run} test runs · ${s.tests_passed} ✓ · ${s.tests_failed} ✗</span>` : ''}
    ${s.lints_run ? `<span class="outcome-chip">🪮 ${s.lints_run} lint runs</span>` : ''}
    ${s.builds_run ? `<span class="outcome-chip">🛠 ${s.builds_run} build runs</span>` : ''}
  </div>`;
}

function renderThrashSummary(files) {
  const hotspots = files.filter((f) => f.thrash.thrash > 0).slice(0, 8);
  if (!hotspots.length) return '';
  const rows = hotspots.map((f) =>
    `<tr><td>${escapeHtml(f.path)}</td><td class="num">${f.actions.length}</td><td class="num">${f.thrash.reverted}</td><td class="num">${f.thrash.changed_later}</td><td class="num">${f.thrash.thrash}</td></tr>`
  ).join('');
  return `<div class="thrash-summary">
    <h4>Thrash hotspots</h4>
    <table>
      <thead><tr><th>file</th><th class="num">edits</th><th class="num">reverted</th><th class="num">changed</th><th class="num">score</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  </div>`;
}

function renderInterventionsAtTop(interventions) {
  if (!interventions.length) return '';
  const seen = new Set();
  const dedup = [];
  for (const i of interventions) {
    const k = i.raw_text.slice(0, 100);
    if (seen.has(k)) continue;
    seen.add(k);
    dedup.push(i);
  }
  const items = dedup.slice(0, 12).map((i) => {
    if (i.meta?.fork_text) {
      return `<div class="intervention qa">
        <div class="qa-label">Claude asked</div>
        <div class="qa-claude">${escapeHtml(i.meta.fork_text)}</div>
        <div class="qa-label">You said</div>
        <div class="qa-user">${escapeHtml(i.raw_text)}</div>
      </div>`;
    }
    return `<div class="intervention simple">${escapeHtml(i.raw_text)}</div>`;
  }).join('');
  return `<h2 class="section-h">Your calls (${dedup.length})</h2>${items}`;
}

function renderFileSection(f, ctx, openFirst) {
  const ghUrl = githubBlobUrl({
    base: ctx.github_base, branch: ctx.branch, repoRoot: ctx.repo_root, absFilePath: f.path,
  });
  const filename = `<a class="fp" href="${ghUrl ?? '#'}" ${ghUrl ? 'target="_blank" rel="noopener"' : ''}>${escapeHtml(f.path)}</a>`;
  const ac = f.alignment_counts;
  const badges = [];
  if (ac.kept)         badges.push(`<span class="badge-align kept">${ac.kept} kept</span>`);
  if (ac.reverted)     badges.push(`<span class="badge-align reverted">${ac.reverted} reverted</span>`);
  if (ac['changed-later']) badges.push(`<span class="badge-align changed-later">${ac['changed-later']} changed</span>`);
  if (ac['not-in-pr']) badges.push(`<span class="badge-align not-in-pr">${ac['not-in-pr']} not-in-PR</span>`);
  if (f.thrash.thrash > 0) badges.push(`<span class="badge-align reverted">thrash ${f.thrash.thrash}</span>`);

  const why = renderFileWhy(f);
  const edits = renderFileEdits(f, ctx);

  return `<details class="file-section"${openFirst ? ' open' : ''}>
    <summary>
      <span class="fp">${filename}</span>
      <span class="badges">${badges.join('')}</span>
      <span class="meta" style="margin-left:auto">${f.actions.length} action(s) · ${f.session_ids.length} session(s)</span>
    </summary>
    <div class="body">
      ${why}
      <h5>Edits in order</h5>
      ${edits}
    </div>
  </details>`;
}

function renderFileWhy(f) {
  if (!f.decisions.length && !f.interventions.length) return '';
  const decs = f.decisions.slice(0, 6).map((d) => `<li class="dec">${escapeHtml(d.raw_text)}</li>`).join('');
  const ints = f.interventions.slice(0, 6).map((i) => `<li class="int">📌 ${escapeHtml(i.raw_text)}</li>`).join('');
  return `<div class="why">
    ${decs ? `<h5>Why this file was touched</h5><ul>${decs}</ul>` : ''}
    ${ints ? `<h5>Your steering on this file</h5><ul>${ints}</ul>` : ''}
  </div>`;
}

function renderFileEdits(f, ctx) {
  const items = f.actions.map((a) => {
    const align = a._alignment ?? 'unknown';
    const alignBadge = `<span class="badge-align ${align}">${align}</span>`;
    const diff = renderActionDiff(a);
    const meta = a.meta ?? {};
    const stamp = a.timestamp ? `<span class="meta" style="margin-left:auto">${escapeHtml(a.timestamp.slice(0,16).replace('T',' '))}</span>` : '';
    const t = meta.turn_tokens;
    const tokChip = t
      ? `<span class="turn-tok" title="in: ${(t.input||0).toLocaleString()} · out: ${(t.output||0).toLocaleString()} · cache_read: ${(t.cache_read||0).toLocaleString()} · cache_create: ${(t.cache_creation||0).toLocaleString()} · billable: ${(t.billable||0).toLocaleString()}">⛁ ${fmtTokens(t.billable)}</span>`
      : '';
    return `<li class="action" style="display:flex; flex-direction:column;">
      <div style="display:flex; align-items:center; gap:6px; flex-wrap:wrap;">
        <span class="tool-name">${escapeHtml(meta.tool_name ?? 'Action')}</span>
        ${alignBadge}
        ${tokChip}
        ${stamp}
      </div>
      ${diff}
    </li>`;
  }).join('');
  return `<ul class="actions-under">${items}</ul>`;
}

function renderActionDiff(a) {
  const tool = a.meta?.tool_name;
  if (tool === 'Edit' || tool === 'MultiEdit') {
    const oldS = a.meta?.old_string ?? '';
    const newS = a.meta?.new_string ?? '';
    if (!oldS && !newS) return '';
    const lines = collapseContext(diffLines(oldS, newS), 2);
    return wrapDiff('diff', lines);
  }
  if (tool === 'Write') {
    const newS = a.meta?.new_string ?? '';
    if (!newS) return '';
    const lines = String(newS).split('\n').slice(0, 80).map((text) => ({ type: '+', text }));
    return wrapDiff('new file', lines);
  }
  if (tool === 'Bash') {
    return `<code class="tool-cmd">${escapeHtml(a.meta?.command ?? '')}</code>`;
  }
  return '';
}

function wrapDiff(label, lines) {
  const body = lines
    .map((d) => {
      const cls = d.type === '+' ? 'add' : d.type === '-' ? 'del' : 'ctx';
      const gutter = d.type === ' ' ? ' ' : d.type;
      return `<span class="ln ${cls}"><span class="ln-gutter">${gutter}</span>${escapeHtml(d.text)}</span>`;
    })
    .join('');
  return `<details class="diff"><summary>${escapeHtml(label)}</summary><pre>${body}</pre></details>`;
}

function renderSessionsList(story) {
  if (!story.session_ids.length) return '';
  return `<h2 class="section-h">Sessions in this PR (${story.session_ids.length})</h2>
    <div class="session-toc">${story.session_ids.map((id) => `<span><code>${escapeHtml(id.slice(0,8))}</code></span>`).join('')}</div>`;
}

function oneLine(s) {
  return String(s ?? '').replace(/\s+/g, ' ').trim();
}
