import { escapeHtml } from '../util/escape.js';
import { BASE_CSS } from './templates/base.css.js';
import { projectNameFromCwd } from '../util/paths.js';
import { diffLines, collapseContext } from '../util/diff.js';
import { githubBlobUrl } from '../util/git.js';
import { compileGlobs } from '../util/claude-md.js';

function fmtTokens(n) {
  n = +n || 0;
  if (n === 0) return '—';
  if (n < 1000) return String(n);
  if (n < 1e6) return (n / 1000).toFixed(n < 10000 ? 1 : 0) + 'k';
  return (n / 1e6).toFixed(1) + 'M';
}

function renderToolsHeader(toolCalls) {
  return renderChipMap(toolCalls, 'tool-chip', 8);
}

function renderChipMap(map, cls, limit = 6) {
  if (!map) return '';
  const entries = Object.entries(map)
    .filter(([, n]) => n > 0)
    .sort((a, b) => b[1] - a[1]);
  if (!entries.length) return '';
  const chips = entries
    .slice(0, limit)
    .map(([name, n]) => `<span class="${cls}">${escapeHtml(name)} <b>${n}</b></span>`)
    .join('');
  return `<span class="chip-row">${chips}</span>`;
}

/**
 * Render a per-session timeline as a standalone HTML document or a
 * fragment suitable for embedding.
 * @param {{session_id: string, chapters: import('../timeline.js').Chapter[]}} timeline
 * @param {{meta?: any, fragment?: boolean}} [opts]
 */
export function renderSessionHtml(timeline, opts = {}) {
  const meta = opts.meta ?? {};
  const projectName = meta.displayName || projectNameFromCwd(meta.cwdGuess ?? meta.projectDir ?? '');
  const startedAt = timeline.chapters[0]?.started_at ?? '';
  const endedAt = timeline.chapters[timeline.chapters.length - 1]?.ended_at ?? '';
  const branch = timeline.git_branch ?? null;
  const branchPill = branch
    ? `<span class="branch-pill" title="git branch when session was active">⎇ ${escapeHtml(branch)}</span>`
    : '';
  const tokenStats = meta.tokens
    ? `<span class="stats">${fmtTokens(meta.tokens.billable)} tok billable · in ${(meta.tokens.input||0).toLocaleString()} · out ${(meta.tokens.output||0).toLocaleString()} · cache ${((meta.tokens.cache_read||0)+(meta.tokens.cache_creation||0)).toLocaleString()}</span>`
    : '';
  const toolsStats = renderToolsHeader(meta.toolCalls);
  const skillsStats = renderChipMap(meta.skillsUsed, 'skill-chip');
  const subagentsStats = renderChipMap(meta.subagentsUsed, 'agent-chip');
  const mcpStats = renderChipMap(meta.mcpTools, 'mcp-chip', 6);
  const bashCatStats = renderChipMap(meta.bashCategories, 'bash-chip', 8);
  const slashStats = renderChipMap(meta.slashCommands, 'slash-chip', 6);

  const body = renderTimelineBody(timeline, { branch });

  if (opts.fragment) return body;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(`Session ${timeline.session_id} — ${projectName}`)}</title>
<style>${BASE_CSS}</style>
</head>
<body>
<header class="coding-agent-story-header">
  <h1>${escapeHtml(projectName)} — session</h1>
  ${branchPill}
  <span class="stats">${escapeHtml(timeline.session_id)} · ${escapeHtml(startedAt)} → ${escapeHtml(endedAt)}</span>
  ${tokenStats}
  ${toolsStats}
  ${bashCatStats}
  ${mcpStats}
  ${subagentsStats}
  ${skillsStats}
  ${slashStats}
</header>
<main>
${body}
<footer class="help-foot">Generated by coding-agent-story · all data stays on your machine.</footer>
</main>
</body>
</html>`;
}

export function renderTimelineBody(timeline, opts = {}) {
  if (!timeline.chapters.length) {
    return `<div class="empty">No events extracted from this session.</div>`;
  }
  const branch = opts.branch ?? timeline.git_branch ?? null;
  const isHot = compileGlobs(timeline.important_files ?? []);
  const ctx = {
    branch,
    github_base: timeline.github_base ?? null,
    repo_root: timeline.repo_root ?? null,
    isHot,
  };
  const branchHeader = renderBranchHeader(branch, ctx);
  return [
    branchHeader,
    renderFileSummary(timeline, ctx),
    renderToc(timeline),
    timeline.chapters.map((c) => renderChapter(c, ctx)).join('\n'),
  ].join('\n');
}

function renderBranchHeader(branch, ctx) {
  if (!branch) return '';
  const inside = `⎇ ${escapeHtml(branch)}`;
  let pill;
  if (ctx.github_base && branch !== 'HEAD') {
    const href = `${ctx.github_base}/tree/${encodeURIComponent(branch)}`;
    pill = `<a class="branch-pill" href="${href}" target="_blank" rel="noopener" title="view branch on GitHub">${inside}</a>`;
  } else {
    pill = `<span class="branch-pill">${inside}</span>`;
  }
  return `<div class="session-branch">${pill} <span class="meta">git branch active during this session</span></div>`;
}

function renderFileSummary(timeline, ctx) {
  const counts = new Map();
  for (const c of timeline.chapters) {
    for (const e of c.events) {
      if (e.type !== 'action') continue;
      const fp = e.meta?.file_path;
      if (!fp) continue;
      counts.set(fp, (counts.get(fp) ?? 0) + 1);
    }
  }
  if (counts.size === 0) return '';
  const rows = [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 12)
    .map(([fp, n]) => {
      const hot = ctx?.isHot?.(fp, ctx.repo_root) ? ' hot' : '';
      const tag = hot ? '<span class="hot-tag" title="marked important in CLAUDE.md">★</span> ' : '';
      return `<tr class="${hot.trim()}"><td class="path">${tag}${renderPathLink(fp, ctx)}</td><td class="count">${n}</td></tr>`;
    })
    .join('');
  return `
<div class="file-summary">
  <h4>Files touched (${counts.size})</h4>
  <table><thead><tr><th>path</th><th style="text-align:right">edits</th></tr></thead><tbody>${rows}</tbody></table>
</div>`;
}

function renderToc(timeline) {
  if (timeline.chapters.length <= 1) return '';
  return `<div class="session-toc">${timeline.chapters
    .map((c, i) => `<a href="#${escapeHtml(c.id)}">${i + 1}. ${escapeHtml(c.title || 'Untitled')}</a>`)
    .join('')}</div>`;
}

function renderChapter(c, ctx) {
  const groups = groupDecisionsWithActions(c.events);
  const actionCount = c.events.filter((e) => e.type === 'action').length;

  const interventionsHtml = c.interventions.map(renderIntervention).join('');
  const groupsHtml = groups.length
    ? groups.map((g) => renderDecisionGroup(g, ctx)).join('')
    : '<p class="meta">(no decisions or actions captured in this chapter)</p>';

  return `
<section class="chapter" id="${escapeHtml(c.id)}">
  <h3>${escapeHtml(c.title || 'Untitled')}</h3>
  <div class="meta">${escapeHtml(c.started_at ?? '')} · ${c.files_touched.length} file(s) · ${actionCount} action(s)</div>
  ${interventionsHtml}
  ${groupsHtml}
</section>`;
}

// Walk events in order. Each decision starts a new group; subsequent
// actions/outcomes attach to the most recent decision. Actions that happen
// before any decision land in a leading "unspecified" group.
function groupDecisionsWithActions(events) {
  const groups = [];
  let current = null;
  for (const e of events) {
    if (e.type === 'decision') {
      if (current && (current.decision || current.actions.length || current.outcomes.length)) {
        groups.push(current);
      }
      current = { decision: e, actions: [], outcomes: [] };
    } else if (e.type === 'action') {
      if (!current) current = { decision: null, actions: [], outcomes: [] };
      current.actions.push({ ...e, _outcome: null });
    } else if (e.type === 'outcome') {
      if (!current) current = { decision: null, actions: [], outcomes: [] };
      const tid = e.meta?.tool_use_id;
      const lastAction = current.actions[current.actions.length - 1];
      if (tid && lastAction && lastAction.meta?.tool_use_id === tid) {
        lastAction._outcome = e;
      } else {
        current.outcomes.push(e);
      }
    }
  }
  if (current && (current.decision || current.actions.length || current.outcomes.length)) {
    groups.push(current);
  }
  return groups;
}

function renderDecisionGroup(g, ctx) {
  const origin = decisionOrigin(g.decision);
  const decisionHtml = g.decision
    ? `<div class="decision-text ${origin.cls}">
        <span class="decision-by">${origin.label}</span>
        ${escapeHtml(g.decision.raw_text)}
      </div>`
    : `<div class="decision-text silent">
        <span class="decision-by">no stated intent</span>
        (silent actions — the model edited without first stating why)
      </div>`;
  const actionsHtml = g.actions.length
    ? `<ul class="actions-under">${g.actions.map((a) => renderActionLi(a, ctx)).join('')}</ul>`
    : '';
  const trailingOutcomes = g.outcomes.length
    ? `<ul class="actions-under">${g.outcomes
        .slice(0, 6)
        .map((o) => `<li class="outcome${o.meta?.is_error ? ' error' : ''}">${escapeHtml(o.raw_text)}</li>`)
        .join('')}</ul>`
    : '';
  return `<section class="decision-group ${origin.groupCls}">
    ${decisionHtml}
    ${actionsHtml}
    ${trailingOutcomes}
  </section>`;
}

function decisionOrigin(decision) {
  if (!decision) return { cls: 'silent', groupCls: 'silent', label: '⚠ silent' };
  if (decision.meta?.user_intent) {
    return { cls: 'by-user', groupCls: 'by-user', label: '👤 you asked' };
  }
  return { cls: 'by-claude', groupCls: 'by-claude', label: '🤖 claude' };
}

function renderActionLi(a, ctx) {
  const summary = renderActionSummary(a, ctx);
  const tokens = renderTurnTokens(a);
  const diff = renderActionDiff(a);
  const outcome = a._outcome
    ? `<div class="action-outcome${a._outcome.meta?.is_error ? ' error' : ''}">${escapeHtml(
        a._outcome.raw_text.slice(0, 300),
      )}</div>`
    : '';
  const tool = a.meta?.tool_name ?? '';
  const dataAttrs = [
    `data-tool="${escapeHtml(tool)}"`,
    a.meta?.file_path ? `data-file="${escapeHtml(a.meta.file_path)}"` : '',
    tool === 'Bash' && typeof a.meta?.command === 'string' ? `data-bashcat="${escapeHtml(bashCategoryHint(a.meta.command))}"` : '',
    tool && tool.startsWith('mcp__') ? `data-mcp="${escapeHtml(shortenMcpName(tool))}"` : '',
  ].filter(Boolean).join(' ');
  return `<li class="action" ${dataAttrs}>${summary}${tokens}${diff}${outcome}</li>`;
}

function shortenMcpName(name) {
  const m = String(name).match(/^mcp__([^_]+(?:_[^_]+)*?)__(.+)$/);
  if (!m) return name.replace(/^mcp__/, '');
  const server = m[1].replace(/^claude_ai_/, '').replace(/_/g, ' ').trim();
  return `${server} · ${m[2]}`;
}

const BASH_HINT = [
  ['git', /\bgit\b/], ['test', /\b(npm\s+(?:run\s+)?test|pytest|vitest|jest|go\s+test|cargo\s+test)\b/i],
  ['install', /\b(npm\s+(?:install|i)\b|yarn\s+add\b|pip\s+install\b|brew\s+install\b)/i],
  ['build', /\b(npm\s+(?:run\s+)?build|tsc\b|vite\s+build|webpack|cargo\s+build|docker\s+build|make\b)\b/i],
  ['lint', /\b(eslint|ruff|flake8|prettier|black)\b/i], ['docker', /\bdocker\b/],
  ['find', /\b(find|grep|rg|ag|fd)\b/], ['ls/cat', /^\s*(ls|cat|head|tail|less|more|wc|stat|file)\b/],
  ['curl', /\b(curl|wget)\b/], ['node', /\bnode\b/], ['python', /\b(python|python3|uvx?|poetry)\b/],
];
function bashCategoryHint(cmd) {
  const c = String(cmd || '').trim();
  for (const [k, rx] of BASH_HINT) if (rx.test(c)) return k;
  return 'other';
}

function renderTurnTokens(a) {
  const t = a.meta?.turn_tokens;
  if (!t) return '';
  const tip = `turn tokens · in: ${(t.input||0).toLocaleString()} · out: ${(t.output||0).toLocaleString()} · cache_read: ${(t.cache_read||0).toLocaleString()} · cache_create: ${(t.cache_creation||0).toLocaleString()} · billable: ${(t.billable||0).toLocaleString()}`;
  return ` <span class="turn-tok" title="${escapeHtml(tip)}">⛁ ${escapeHtml(fmtTokens(t.billable))}</span>`;
}

function renderActionSummary(a, ctx) {
  const tool = a.meta?.tool_name ?? '';
  const fp = a.meta?.file_path;
  if (fp && (tool === 'Edit' || tool === 'MultiEdit' || tool === 'Write' || tool === 'NotebookEdit')) {
    return `<span class="tool-name">${escapeHtml(tool)}</span> ${renderPathLink(fp, ctx)}`;
  }
  if (tool === 'Bash') {
    const cmd = a.meta?.command ?? a.raw_text;
    return `<span class="tool-name">Bash</span> <code class="tool-cmd">${escapeHtml(oneLineClip(cmd, 200))}</code>`;
  }
  return escapeHtml(a.raw_text);
}

function renderPathLink(absPath, ctx) {
  const safeText = escapeHtml(absPath);
  const ghUrl = ctx ? githubBlobUrl({
    base: ctx.github_base,
    branch: ctx.branch,
    repoRoot: ctx.repo_root,
    absFilePath: absPath,
  }) : null;
  const vscodeHref = `vscode://file${encodeFilePath(absPath)}`;
  const fileHref = `file://${encodeFilePath(absPath)}`;
  // Show the GitHub link as primary when available; keep local-open links as alternates.
  const primary = ghUrl
    ? `<a class="file-link gh" href="${escapeHtml(ghUrl)}" target="_blank" rel="noopener" title="view on GitHub">${safeText}</a>`
    : `<a class="file-link" href="${vscodeHref}" title="open in VS Code">${safeText}</a>`;
  const alts = ghUrl
    ? ` <a class="file-link-alt" href="${vscodeHref}" title="open in VS Code">VS</a>` +
      ` <a class="file-link-alt" href="${fileHref}" title="open with default app">↗</a>`
    : ` <a class="file-link-alt" href="${fileHref}" title="open with default app">↗</a>`;
  return primary + alts;
}

function encodeFilePath(p) {
  // Preserve "/" separators; encode the rest for URL safety.
  return String(p).split('/').map(encodeURIComponent).join('/');
}

function oneLineClip(s, n) {
  const t = String(s ?? '').replace(/\s+/g, ' ').trim();
  return t.length <= n ? t : t.slice(0, n - 1) + '…';
}

function renderActionDiff(a) {
  const tool = a.meta?.tool_name;
  if (tool === 'Edit' || tool === 'MultiEdit') {
    const oldS = a.meta?.old_string ?? '';
    const newS = a.meta?.new_string ?? '';
    if (!oldS && !newS) return '';
    const lines = collapseContext(diffLines(oldS, newS), 2);
    return wrapDiff('diff', lines);
  }
  if (tool === 'Write') {
    const newS = a.meta?.new_string ?? '';
    if (!newS) return '';
    const lines = String(newS)
      .split('\n')
      .slice(0, 80)
      .map((text) => ({ type: '+', text }));
    return wrapDiff('new file', lines);
  }
  return '';
}

function wrapDiff(label, lines) {
  const body = lines
    .map((d) => {
      const cls = d.type === '+' ? 'add' : d.type === '-' ? 'del' : 'ctx';
      const gutter = d.type === ' ' ? ' ' : d.type;
      return `<span class="ln ${cls}"><span class="ln-gutter">${gutter}</span>${escapeHtml(d.text)}</span>`;
    })
    .join('');
  return `<details class="diff"><summary>${escapeHtml(label)}</summary><pre>${body}</pre></details>`;
}

function renderIntervention(i) {
  const forkText = i.meta?.fork_text;
  if (forkText) {
    return `<div class="intervention qa">
      <div class="qa-label">Claude asked</div>
      <div class="qa-claude">${escapeHtml(forkText)}</div>
      <div class="qa-label">You said</div>
      <div class="qa-user">${escapeHtml(i.raw_text)}</div>
    </div>`;
  }
  return `<div class="intervention simple">${escapeHtml(i.raw_text)}</div>`;
}
